item {
    id:1
    name:"goLeft"
}

item {
    id:2
    name:"warningLeft"
}

item {
    id:3
    name:"go"
}

item {
    id:4
    name:"stopLeft"
}

item {
    id:5
    name:"stop"
}

item {
    id:6
    name:"warning"
}
