services: 
  mysqldb:
    image: michaelingrum/signal-db:10.5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    pull_policy: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASS
    ports:
      - $MYSQL_DOCKER_PORT:3306
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  app:
    build: .
    image: signalsensebox1
    depends_on:
      - mysqldb
    links:
      - "mysqldb:database"
    volumes:
      - ./:/app/
    stdin_open: true
    tty: true
    ports:
      - $SERVER_PORT:$SERVER_PORT
    command: npm start

