services: 
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASS
    ports:
      - 3306:3306

    volumes: 
      - db-config3:/etc/mysql
      - db-data3:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  app:
    build: .
    image: signalsensebox1
    # environment:
      # MYSQL_APP_USER: $MYSQL_APP_USER
      # MYSQL_APP_PASS: $MYSQL_APP_PASS
      # MYSQL_DATABASE: $MYSQL_DATABASE
    depends_on:
      - mysqldb
    links:
      - "mysqldb:database"
    volumes:
      - ./:/app/
    stdin_open: true
    tty: true
    ports:
      - 3000:3000

volumes: 
  db-config3:
  db-data3:
