insert into LightStateRef(lightStateRefID, state) values (0, 'NOT_FOUND');
insert into LightStateRef(lightStateRefID, state) values (1, 'RED');
insert into LightStateRef(lightStateRefID, state) values (2, 'YELLOW');
insert into LightStateRef(lightStateRefID, state) values (3, 'GREEN');
insert into LightStateRef(lightStateRefID, state) values (4, 'LEFT_RED');
insert into LightStateRef(lightStateRefID, state) values (5, 'LEFT_YELLOW');
insert into LightStateRef(lightStateRefID, state) values (6, 'LEFT_GREEN');
insert into LightStateRef(lightStateRefID, state) values (7, 'RIGHT_RED');
insert into LightStateRef(lightStateRefID, state) values (8, 'RIGHT_YELLOW');
insert into LightStateRef(lightStateRefID, state) values (9, 'RIGHT_GREEN');
insert into PhaseType values ('1', 'DRIVING_LANE');