name: Deploy EC2
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  merge-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: rsync over ssh
        run: |
          ssh deployer@ec2-54-183-188-143.us-west-1.compute.amazonaws.com " ./deploy"
